# Generated by Django 2.2 on 2020-12-17 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='MonthName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='PupilMonthMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_1', models.CharField(blank=True, max_length=8)),
                ('mark_2', models.CharField(blank=True, max_length=8)),
                ('mark_3', models.CharField(blank=True, max_length=8)),
                ('mark_4', models.CharField(blank=True, max_length=8)),
                ('mark_5', models.CharField(blank=True, max_length=8)),
                ('mark_6', models.CharField(blank=True, max_length=8)),
                ('mark_7', models.CharField(blank=True, max_length=8)),
                ('mark_8', models.CharField(blank=True, max_length=8)),
                ('mark_9', models.CharField(blank=True, max_length=8)),
                ('mark_10', models.CharField(blank=True, max_length=8)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.Lesson')),
                ('month_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.MonthName')),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
