# Generated by Django 2.2 on 2020-12-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupilmonthmarks',
            name='mark_11',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='pupilmonthmarks',
            name='mark_12',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='pupilmonthmarks',
            name='mark_13',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='pupilmonthmarks',
            name='mark_14',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='pupilmonthmarks',
            name='mark_15',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
